# Generated by Django 4.2 on 2023-04-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=30, unique=True, verbose_name='Order name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('status', models.CharField(choices=[('New', 'New'), ('In Process', 'In Process'), ('Stored', 'Stored'), ('Complete', 'Complete')], default='New', max_length=15)),
            ],
        ),
    ]
